services:
  - type: web
    name: nextjs-telegram-bot
    env: node
    plan: starter
    buildCommand: npm ci && npm run build
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: NEXT_PUBLIC_WEBAPP_URL
        sync: false
      - key: NEXT_PUBLIC_THIRDWEB_CLIENT_ID
        sync: false
      - key: NEXT_PUBLIC_AUTH_PHRASE
        sync: false
      - key: SPONSOR_PRIVATE_KEY
        sync: false